/**
 * Data-Driven Testing — Excel (.xlsx) source
 * ============================================
 * Demonstrates:
 *  • Generate an Excel file programmatically (SheetJS / xlsx package)
 *  • Read the file synchronously at module-evaluation time
 *  • Create one test() per row — identical pattern to jsonDriven.spec.js
 *  • Column types: strings, numbers, booleans (xlsx preserves JS types)
 *
 * Key difference vs JSON:
 *   Excel is preferred when:
 *     — Business analysts / QA own the test data (familiar tooling)
 *     — Data includes formulas, formatting, or multiple sheets
 *     — Test data is already maintained in a spreadsheet
 *
 * Install dependency first:  npm install xlsx
 *
 * File created at: utils/data/loginScenarios.xlsx
 * Test site: https://www.saucedemo.com  (via playwright.config.js baseURL)
 */

import { test, expect }           from '@playwright/test';
import { existsSync }              from 'fs';
import { join, dirname }           from 'path';
import { fileURLToPath }           from 'url';
import { writeExcel, readExcel }   from '../../utils/excelHelper.js';
import { LoginPage }               from '../../pages/LoginPage.js';

const __dirname  = dirname(fileURLToPath(import.meta.url));
const EXCEL_PATH = join(__dirname, '../../utils/data/loginScenarios.xlsx');

// ── Seed data ─────────────────────────────────────────────────────────────────
// This mirrors loginScenarios.json so you can compare both approaches side-by-side.
// In a real project the file would already exist (committed to the repo or
// generated by a CI setup step).  Here we create it on-the-fly if absent.
const SEED_ROWS = [
  { id: 1, description: 'standard_user logs in successfully',         username: 'standard_user',          password: 'secret_sauce',   expectSuccess: true,  errorContains: '' },
  { id: 2, description: 'locked_out_user sees locked error',          username: 'locked_out_user',         password: 'secret_sauce',   expectSuccess: false, errorContains: 'Sorry, this user has been locked out' },
  { id: 3, description: 'wrong password shows credential mismatch',   username: 'standard_user',          password: 'wrong_password', expectSuccess: false, errorContains: 'Username and password do not match' },
  { id: 4, description: 'empty username shows validation error',      username: '',                       password: 'secret_sauce',   expectSuccess: false, errorContains: 'Username is required' },
  { id: 5, description: 'empty password shows validation error',      username: 'standard_user',          password: '',               expectSuccess: false, errorContains: 'Password is required' },
  { id: 6, description: 'performance_glitch_user reaches inventory',  username: 'performance_glitch_user', password: 'secret_sauce',  expectSuccess: true,  errorContains: '' },
];

// ── Create the Excel file once if it does not already exist ───────────────────
// This runs synchronously when the module is first loaded by the test runner,
// so the file is ready before any test body executes.
if (!existsSync(EXCEL_PATH)) {
  writeExcel(EXCEL_PATH, 'LoginScenarios', SEED_ROWS);
  console.log(`[excelDriven] Created seed file: ${EXCEL_PATH}`);
}

// ── Read the Excel rows at module-evaluation time ─────────────────────────────
// readExcel() returns an array of plain objects, one per data row.
// Column headers (row 1) become the object keys.
const scenarios = readExcel(EXCEL_PATH, 'LoginScenarios');

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 1 — Functional tests generated from Excel rows
// ─────────────────────────────────────────────────────────────────────────────

test.describe.configure({ mode: 'parallel' });

test.describe('Data-driven login tests — Excel (.xlsx)', () => {

  for (const row of scenarios) {
    test(`[${row.id}] ${row.description}`, async ({ page }) => {
      const loginPage = new LoginPage(page);
      await loginPage.goto();
      await loginPage.loginAs(String(row.username), String(row.password));

      if (row.expectSuccess) {
        await expect(page).toHaveURL(/inventory/, { timeout: 10_000 });
      } else {
        const errorText = await loginPage.getErrorMessage();
        expect(errorText).toContain(row.errorContains);
      }
    });
  }

});

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 2 — Excel utility demos (write + read round-trip)
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Excel utility — writeExcel / readExcel', () => {

  const ROUND_TRIP_PATH = join(__dirname, '../../utils/data/roundTrip.xlsx');

  test.afterAll(() => {
    // Clean up the round-trip file
    if (existsSync(ROUND_TRIP_PATH)) {
      import('fs').then(({ unlinkSync }) => unlinkSync(ROUND_TRIP_PATH));
    }
  });

  test('writeExcel creates a file that readExcel can read back', () => {
    const original = [
      { name: 'Alice', score: 95, passed: true  },
      { name: 'Bob',   score: 42, passed: false },
    ];

    writeExcel(ROUND_TRIP_PATH, 'Results', original);
    expect(existsSync(ROUND_TRIP_PATH)).toBe(true);

    const read = readExcel(ROUND_TRIP_PATH, 'Results');
    expect(read).toHaveLength(2);
    expect(read[0].name).toBe('Alice');
    expect(read[1].score).toBe(42);
  });

  test('readExcel defaults to the first sheet when no name is provided', () => {
    const rows = readExcel(EXCEL_PATH); // no sheet name argument
    expect(Array.isArray(rows)).toBe(true);
    expect(rows.length).toBeGreaterThan(0);
  });

  test('readExcel row count matches the number of data rows in the seed', () => {
    const rows = readExcel(EXCEL_PATH, 'LoginScenarios');
    // Header row is NOT included in the output — only data rows
    expect(rows).toHaveLength(SEED_ROWS.length);
  });

  test('each Excel row has all expected column keys', () => {
    const rows = readExcel(EXCEL_PATH, 'LoginScenarios');
    const REQUIRED_KEYS = ['id', 'description', 'username', 'password', 'expectSuccess', 'errorContains'];

    for (const row of rows) {
      for (const key of REQUIRED_KEYS) {
        expect(row, `Row ${row.id} is missing column "${key}"`).toHaveProperty(key);
      }
    }
  });

});
